image: alpine:latest

stages:
  - pre-build
  - build
  - test
  - dev
  - stg
  - integration-test
  - prod

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  needs:
    - build-job
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  needs:
    - build-job
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20
    
deploy-dev:
  stage: dev
  needs:
    - build-job
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."

deploy-stg:
  stage: stg
  needs:
    - build-job
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."

qa-stg:
  stage: integration-test
  needs:
    - deploy-stg
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
